#!/usr/bin/env bash

# Install Developer Tools
xcode-select --install

# Install Ansible
pip3 install --ignore-installed ansible

# Set up PATH for Ansible
PYTHON_USER_BASE=$(python3 -m site --user-base)
export PATH="${PYTHON_USER_BASE}/bin:$PATH"

ansible-playbook local.yml --ask-become-pass --ask-vault-pass
