- hosts: localhost
  collections:
    - ansible.posix
    - community.general
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/Developer/unkrich"
    work: "{{ lookup('env', 'HOME') }}/Developer/superpowerdotcom"
    brew_cask_packages:
      - 1password
      - activitywatch
      - arc
      - claude
      - claude-code
      - cron
      - discord
      - docker
      - ghostty
      - google-chrome
      - hazel
      - figma
      - font-meslo-lg-nerd-font
      - font-hack-nerd-font
      - notion
      - openscad
      - pgadmin4
      - postman
      - sf-symbols
      - sublime-text
      - superhuman
      - tailscale
      - zoom
    brew_packages:
      - autoconf
      - awscli
      - defaultbrowser
      - direnv
      - docker-compose
      - docker-machine
      - dockutil
      - gh
      - gnupg
      - helm
      - jq
      - postgresql@14
      - stow
      - tmux
      - tree
      - zsh-syntax-highlighting
    dockitems_to_persist:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 1
      - name: Messages
        path: "/Applications/Messages.app"
        pos: 2
      - name: Claude
        path: "/Applications/CLaude.app"
        pos: 3
      - name: Superhuman
        path: "/Applications/Superhuman.app"
        pos: 4
      - name: Notion Calendar
        path: "/Applications/Notion\ Calendar.app"
        pos: 5
      - name: Notion
        path: "/Applications/Notion.app"
        pos: 6
      - name: Ghostty
        path: "/Applications/Ghostty.app"
        pos: 7
      - name: System Settings
        path: "/Applications/System Settings.app"
        pos: 8
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: false
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/setup-brew.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/osx-defaults/osx-defaults-apple.yml
    - include_tasks: tasks/osx-defaults/osx-defaults-chrome.yml
    - include_tasks: tasks/osx-defaults/osx-defaults-dock.yml
    - include_tasks: tasks/osx-defaults/osx-defaults-finder.yml
    - include_tasks: tasks/osx-defaults/osx-defaults-keyboard.yml
    - include_tasks: tasks/osx-defaults/osx-defaults-spotlight.yml
    # - include_tasks: tasks/dotfiles.yml
    # - include_tasks: tasks/zsh-setup.yml
    # - include_tasks: tasks/sketchybar-setup.yml
    # - include_tasks: tasks/skhd-setup.yml
    # - include_tasks: tasks/yabai-setup.yml
