- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/Developer/unkrich"
    work: "{{ lookup('env', 'HOME') }}/Developer/superpowerdotcom"
    brew_taps:
      - FelixKratz/formulae
    brew_cask_packages:
      - 1password
      - adoptopenjdk
      - arc
      - cron
      - discord
      - docker
      - google-chrome
      - hammerspoon
      - hazel
      - karabiner-elements
      - iterm2
      - ledger-live
      - linear-linear
      - notion
      - openscad
      - pgadmin4
      - postman
      - qbittorrent
      - slack
      - sublime-text
      - superhuman
      - tailscale
      - ultimaker-cura
      - zoom
    brew_packages:
      - autoconf
      - awscli
      - chruby
      - defaultbrowser
      - direnv
      - docker-compose
      - docker-machine
      - dockutil
      - dopplerhq/cli/doppler
      - eslint
      - fzf
      - fzy
      - gmailctl
      - helm
      - jq
      - koekeishiya/formulae/skhd
      - koekeishiya/formulae/yabai
      - kompose
      - kops
      - kubectl
      - k9s
      - lua-language-server
      - minikube
      - neovim
      - node
      - nvm
      - postgresql@14
      - prettier
      - prettierd
      - pyright
      - ripgrep
      - ruby-install
      - rust-analyzer
      - sketchybar
      - stow
      - temporal
      - temporalio/brew/tcld
      - terraform
      - thefuck
      - tmux
      - typescript-language-server
      - tree
      - virtualenv
      - yarn
      - zsh-syntax-highlighting
    dockitems_to_persist:
      - name: Arc
        path: "/Applications/Arc.app"
        pos: 1
      - name: Messages
        path: "/Applications/Messages.app"
        pos: 2
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 3
      - name: Discord
        path: "/Applications/Discord.app"
        pos: 4
      - name: Notion Calendar
        path: "/Applications/Notion\ Calendar.app"
        pos: 5
      - name: Superhuman
        path: "/Applications/Superhuman.app"
        pos: 6
      - name: Notion
        path: "/Applications/Notion.app"
        pos: 7
      - name: Linear
        path: "/Applications/Linear.app"
        pos: 8
      - name: iTerm
        path: "/Applications/iTerm.app"
        pos: 9
      - name: System Settings
        path: "/Applications/System Settings.app"
        pos: 10
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: false
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/setup-brew.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/personal-projects.yml
    - include: tasks/osx-defaults/osx-defaults-apple.yml
    - include: tasks/osx-defaults/osx-defaults-dock.yml
    - include: tasks/osx-defaults/osx-defaults-finder.yml
    - include: tasks/osx-defaults/osx-defaults-keyboard.yml
    - include: tasks/dotfiles.yml
    - include: tasks/sketchybar-setup.yml
    - include: tasks/skhd-setup.yml
    - include: tasks/yabai-setup.yml
