- name: unkrich exists
  shell: mkdir -p {{ personal }}
  tags:
    - personal-project

- name: Dotfiles
  become_user: kevinunkrich
  become: true
  ansible.builtin.git:
    repo: 'git@github.com:unkrich/dotfiles.git'
    dest: "{{ personal }}/dotfiles"
    key_file: ~/.ssh/id_rsa
  tags:
    - personal-project
