# - name: Installing stow
# apt: name=stow
# tags:
# - install
# - dotfiles
# - stow

# - name: Cloning .dotfiles
# ansible.builtin.git:
# repo: 'git@github.com:unkrich/dotfiles.git'
# dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
# recursive: yes
# update: yes
# accept_hostkey: yes
# version: master
# tags:
# - install
# - dotfiles
# - stow

- name: Stow dotfiles
  shell: "cd {{ personal }}/dotfiles && ./macos"
  tags:
    - install
    - dotfiles
    - stow

      # - name: Start skhd
      # command: skhd --start-service
      # - name: Restart skhd
      # command: /usr/local/bin/brew services restart skhd
