# - name: Authenticate github
#   shell: ssh -T git@github.com

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "kevin@unkri.ch"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "unkrich"
  tags:
  - git-personal
