- name: unkrich exists
  shell: mkdir -p {{ personal }}
  tags:
    - personal-project

- name: Ansible
  ansible.builtin.git:
    repo: 'git@github.com:unkrich/ansible.git'
    dest: "{{ personal }}/ansible"
  tags:
    - work-project
