- name: unkrich exists
  shell: mkdir -p {{ personal }}
  tags:
    - personal-project

# - name: Ansible
#   become: true
#   ansible.builtin.git:
#     repo: 'git@github.com:unkrich/ansible.git'
#     dest: "{{ personal }}/ansible"
#     key_file: ~/.ssh/id_rsa
#   tags:
#     - personal-project

- name: Dotfiles
  become_user: kevinunkrich
  become: true
  ansible.builtin.git:
    repo: 'git@github.com:unkrich/dotfiles.git'
    dest: "{{ personal }}/dotfiles"
    key_file: ~/.ssh/id_rsa
  tags:
    - personal-project

- name: ZMK Config
  become_user: kevinunkrich
  become: true
  ansible.builtin.git:
    repo: 'git@github.com:unkrich/zmk-config-zen-2.git'
    dest: "{{ personal }}/zmk-config-zen-2"
    key_file: ~/.ssh/id_rsa
  tags:
    - personal-project
