- name: Dockutil | Remove all dock items
  shell: dockutil --remove all --no-restart
  tags:
    - dock
    - macos
    - osx_defaults

- name: Dockutil | Adding items
  shell: dockutil --add '{{ item.path }}' --position {{ item.pos }}
  with_items: "{{ dockitems_to_persist }}"
  loop_control:
    label: "{{item}}"
  tags:
    - dock
    - macos
    - osx_defaults


- name: Hide Dock and set to left-hand side
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    value: left
  tags:
    - dock
    - macos
    - osx_defaults

- name: Remove auto-hiding Dock delay
  osx_defaults:
    domain: com.apple.Dock
    key: autohide-delay
    value: 0.0001
  tags:
    - dock
    - macos
    - osx_defaults

- name: Remove animation when hiding/showing Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    value: 0
  tags:
    - dock
    - macos
    - osx_defaults

- name: Automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    value: true
  tags:
    - dock
    - macos
    - osx_defaults

- name: Don't show recent applications in Dock
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    value: false
  tags:
    - dock
    - macos
    - osx_defaults

- name: Set Dock icon size to 30 pixels
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    value: 30
  tags:
    - dock
    - macos
    - osx_defaults

- name: Speed up Mission Control animations
  osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    value: 0.1
  tags:
    - dock
    - macos
    - osx_defaults

- name: Disable automatic capitalization
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    value: false
  tags:
    - text
    - keyboard
    - macos
    - osx_defaults
  description: "Disable automatic capitalization as it's annoying when typing code"

- name: Disable smart dashes
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    value: false
  tags:
    - text
    - keyboard
    - macos
    - osx_defaults
  description: "Disable smart dashes as they're annoying when typing code"

- name: Disable automatic period substitution
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    value: false
  tags:
    - text
    - keyboard
    - macos
    - osx_defaults
  description: "Disable automatic period substitution as it's annoying when typing code"

- name: Disable smart quotes
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    value: false
  tags:
    - text
    - keyboard
    - macos
    - osx_defaults
  description: "Disable smart quotes as they're annoying when typing code"

- name: Disable automatic spelling correction
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    value: false
  tags:
    - text
    - keyboard
    - macos
    - osx_defaults
  description: "Disable auto-correct"

- name: Set AppleKeyboardUIMode
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    value: 3
  tags:
    - keyboard
    - macos
    - osx_defaults
  description: "Set caps lock to control (e.g. enable Tab in modal dialogs)"

- name: Set initial key repeat
  osx_defaults:
    domain: -g
    key: InitialKeyRepeat
    value: 10
  tags:
    - keyboard
    - macos
    - osx_defaults
  description: "Set keyboard delay / repeat"

- name: Set key repeat
  osx_defaults:
    domain: -g
    key: KeyRepeat
    value: 1
  tags:
    - keyboard
    - macos
    - osx_defaults
  description: "Set keyboard delay / repeat"

- name: Run capslocktoctl script
  script: scripts/capslocktoctl.scpt
  tags:
    - keyboard
    - macos
    - osx_defaults
  description: "Set caps lock to control"

- name: Show filename extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    value: true
    state: present
  tags: 
    - finder
    - macos
    - osx_defaults

- name: Show dotfiles
  osx_defaults:
    domain: -g
    key: AppleShowAllFiles
    value: true
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Show full path in Finder
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    value: true
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Enable quitting Finder via ⌘ + Q
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    value: true
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Show icons for various desktop items
  osx_defaults:
    domain: com.apple.finder
    key: "{{ item.key }}"
    value: true
    state: present
  loop:
    - { key: ShowExternalHardDrivesOnDesktop }
    - { key: ShowHardDrivesOnDesktop }
    - { key: ShowMountedServersOnDesktop }
    - { key: ShowRemovableMediaOnDesktop }
  tags:
    - finder
    - macos
    - osx_defaults

- name: Disable file extension change warning
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    value: false
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    value: true
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Avoid creating .DS_Store files on USB volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    value: true
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Automatically open new Finder window when volume is mounted
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: "{{ item.key }}"
    value: true
    state: present
  loop:
    - { key: auto-open-ro-root }
    - { key: auto-open-rw-root }
  tags:
    - finder
    - macos
    - osx_defaults

- name: Open window for new removable disk
  osx_defaults:
    domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    value: true
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Set default Finder view style to list view
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    value: "Nlsv"
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Disable "Are you sure you want to open this application?" dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    value: false
    state: present
  tags:
    - finder
    - macos
    - osx_defaults

- name: Restart Finder
  shell: killall Finder
  changed_when: false
  tags:
    - finder
    - macos
    - osx_defaults

- name: Set Spotlight search categories
  osx_defaults:
    domain: com.apple.spotlight
    key: orderedItems
    value:
      - '{"enabled" = 1;"name" = "APPLICATIONS";}'
      - '{"enabled" = 1;"name" = "SYSTEM_PREFS";}'
      - '{"enabled" = 1;"name" = "DIRECTORIES";}'
      - '{"enabled" = 1;"name" = "PDF";}'
      - '{"enabled" = 1;"name" = "FONTS";}'
      - '{"enabled" = 0;"name" = "DOCUMENTS";}'
      - '{"enabled" = 0;"name" = "MESSAGES";}'
      - '{"enabled" = 0;"name" = "CONTACT";}'
      - '{"enabled" = 0;"name" = "EVENT_TODO";}'
      - '{"enabled" = 0;"name" = "IMAGES";}'
      - '{"enabled" = 0;"name" = "BOOKMARKS";}'
      - '{"enabled" = 0;"name" = "MUSIC";}'
      - '{"enabled" = 0;"name" = "MOVIES";}'
      - '{"enabled" = 0;"name" = "PRESENTATIONS";}'
      - '{"enabled" = 0;"name" = "SPREADSHEETS";}'
      - '{"enabled" = 0;"name" = "SOURCE";}'
      - '{"enabled" = 0;"name" = "MENU_DEFINITION";}'
      - '{"enabled" = 0;"name" = "MENU_OTHER";}'
      - '{"enabled" = 0;"name" = "MENU_CONVERSION";}'
      - '{"enabled" = 0;"name" = "MENU_EXPRESSION";}'
      - '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}'
      - '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
  when: ansible_os_family == 'Darwin'
  tags:
    - spotlight
    - macos
    - osx_defaults

- name: Reload Spotlight settings
  osx_defaults:
    domain: -currentHost
    key: com.apple.spotlight orderedItems
  when: ansible_os_family == 'Darwin'
  tags:
    - spotlight
    - macos
    - osx_defaults

- name: Restart mds
  command: "killall mds > /dev/null 2>&1"
  when: ansible_os_family == 'Darwin'
  tags:
    - spotlight
    - macos
    - osx_defaults

- name: Enable indexing for the main volume
  command: "sudo mdutil -i on / > /dev/null"
  when: ansible_os_family == 'Darwin'
  tags:
    - spotlight
    - macos
    - osx_defaults

- name: Rebuild Spotlight index
  command: "sudo mdutil -E / > /dev/null"
  when: ansible_os_family == 'Darwin'
  tags:
    - spotlight
    - macos
    - osx_defaults

- name: Set Google Chrome as default browser
  command: open -a "Google Chrome" --args --make-default-browser
  args:
    executable: /bin/bash
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Disable sensitive backswipe in Chrome
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    value: false
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Disable sensitive backswipe in Chrome Canary
  osx_defaults:
    domain: com.google.Chrome.canary
    key: AppleEnableSwipeNavigateWithScrolls
    value: false
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Disable mouse backswipe in Chrome
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableMouseSwipeNavigateWithScrolls
    value: false
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Disable mouse backswipe in Chrome Canary
  osx_defaults:
    domain: com.google.Chrome.canary
    key: AppleEnableMouseSwipeNavigateWithScrolls
    value: false
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Use system print dialog and expand it in Chrome
  osx_defaults:
    domain: com.google.Chrome
    key: DisablePrintPreview
    value: true
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Use system print dialog and expand it in Chrome Canary
  osx_defaults:
    domain: com.google.Chrome.canary
    key: DisablePrintPreview
    value: true
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Expand save and print panel by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    value: true
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Expand save and print panel by default (mode 2)
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    value: true
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Expand print panel by default
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    value: true
  tags:
    - chrome
    - macos
    - osx_defaults

- name: Expand print panel by default (print 2)
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint2
    value: true
  tags:
    - chrome
    - macos
    - osx_defaults


###################################
# APPLE                           #
###################################

- name: Disable Ask Siri
  domain: com.apple.assistant.support
  key: "Assistant Enabled"
  type: bool
  value: false
  tags:
    - macos
    - osx_defaults
    - apple

- name: Remove siri icon from status menu
  domain: com.apple.Siri
  key: StatusMenuVisible
  type: bool
  value: false
  tags:
    - macos
    - osx_defaults
    - apple

- name: Prevent Photos from opening automatically when devices are plugged in
  domain: com.apple.ImageCapture
  key: disableHotPlug
  type: bool
  value: true
  tags:
    - macos
    - osx_defaults
    - apple

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  domain: com.apple.TimeMachine
  key: DoNotOfferNewDisksForBackup
  type: bool
  value: true
  tags:
    - macos
    - osx_defaults
    - apple

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  domain: com.apple.TimeMachine
  key: DoNotOfferNewDisksForBackup
  type: bool
  value: true
  tags:
    - macos
    - osx_defaults
    - apple

- name: Create screenshots directory
  shell: mkdir -p ~/Pictures/screenshots
  tags:
  - macos
  - osx_defaults
  - apple

- name: Set screenshots directory
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: ~/Pictures/screenshots
  tags:
    - macos
    - osx_defaults
    - apple

- name: Save screenshots as png
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
  tags:
    - macos
    - osx_defaults
    - apple

      
# # Automatically quit printer app once the print jobs complete
# defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# # Increase sound quality for Bluetooth headphones/headsets
# defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# # Disable animations when opening and closing windows.
# defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

# # Accelerated playback when adjusting the window size.
# defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# # Dont rearrange spaces based on recent use
# defaults write com.apple.dock mru-spaces -bool false

# # Enable bluetooth menu in status bar
# defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist Bluetooth -int 18

# killall Dock

- name: Disable shadow in screenshots
  osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
  tags:
    - macos
    - osx_defaults
    - apple


# Remap Caps Lock to CTRL
- name: Remap caps lock to CTRL
  shell: hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x7000000E0}]}'
  tags:
    - macos
    - osx_defaults
    - keyboard

# Enable full keyboard control - tab in modals
- osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
  tags:
    - macos
    - osx_defaults
    - keyboard

# Delay / Repeat
- osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 10
  tags:
    - macos
    - osx_defaults
    - keyboard
- osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 1
  tags:
    - macos
    - osx_defaults
    - keyboard

  
# Disable automatic period substitution
- osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - keyboard

# Disable smart quotes as they're annoying when typing code
- osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - keyboard

# Disable smart dashes
- osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - keyboard

- name: Disable automatic capitalization
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - keyboard


- name: Disable automatic spelling correction
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - keyboard


- name: Hide dock and set to left-hand side
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left
  tags:
    - macos
    - osx_defaults
    - dock

- name: Don't show recent applications in dock
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - dock

- name: Set icon size of Dock items to 30 pixels
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 30
  tags:
    - macos
    - osx_defaults
    - dock

- name: Speed up Mission Control animation
  osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.1
  tags:
    - macos
    - osx_defaults
    - dock

- name: Automatically hide dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  tags:
    - macos
    - osx_defaults
    - dock

- name: Remove the auto-hiding Dock delay
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0.0001
  tags:
    - macos
    - osx_defaults
    - dock

- name: Remove the auto-hiding Dock animation
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0.0001
  tags:
    - macos
    - osx_defaults
    - dock

- name: Don't rearrange spaces based on recent use
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - dock

- name: Don't animate app launches
  osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: false
  tags:
    - macos
    - osx_defaults
    - dock

- name: Autohide menubar
  osx_defaults:
    domain: NSGlobalDomain
    key: _HIHideMenuBar
    type: bool
    value: true
  tags:
    - macos
    - osx_defaults
    - dock



  #### FINDER ####

  # Preferences - show filename extensions
  # system.defaults.NSGlobalDomain.AppleShowAllExtensions = true;

  # Enable showing dotfiles (just hold Cmd + Shift + . (dot) in a finder window)
  # system.defaults.NSGlobalDomain.AppleShowAllFiles = true;

  # Show full path in finder
  # system.defaults.finder._FXShowPosixPathInTitle = true;
 
  # Disable the "Are you sure you want to open this application" dialog
  # system.defaults.LaunchServices.LSQuarantine = false;

  # Disable the warning when changing a file extension
  # system.defaults.finder.FXEnableExtensionChangeWarning = false;

  # Use list view in all Finder windows by default
  # system.defaults.finder.FXPreferredViewStyle = "Nlsv";
  
 # Disable animations when opening and closing windows 
  # system.defaults.NSGlobalDomain.NSAutomaticWindowAnimationsEnabled = false;

  # Accelerated playback when adjusting the window size.
  # system.defaults.NSGlobalDomain.NSWindowResizeTime = 0.001;
  
  # Finder: allow quitting via command Q
  # system.defaults.finder.QuitMenuItem = true;

  # Expand save and print panel by default
  # system.defaults.NSGlobalDomain.NSNavPanelExpandedStateForSaveMode = true;
  # system.defaults.NSGlobalDomain.NSNavPanelExpandedStateForSaveMode2 = true;
  # system.defaults.NSGlobalDomain.PMPrintingExpandedStateForPrint = true;
  # system.defaults.NSGlobalDomain.PMPrintingExpandedStateForPrint2 = true;

