- name: Chrome - get default browser
  shell: defaultbrowser | sed 's/Current:\ //' | head -1
  register: defaultbrowser_value
  changed_when: False
  tags:
    - chrome
    - install
    - macos

- name: Chrome - set as default browser
  command: defaultbrowser chrome
  become: true
  when: defaultbrowser_value.stdout != "chrome"
  tags:
    - chrome
    - install
    - macos
