- name: Check if skhd plist file exists
  stat:
    path: ~/Library/LaunchAgents/com.koekeishiya.skhd.plist
  register: register_name

- name: Install skhd service file
  shell: skhd --install-service
  when:
    - not register_name.stat.exists

- name: Start skhd
  shell: skhd --start-service
  when:
    - not register_name.stat.exists
