- name: Install skhd service
  shell: skhd --install-service
  ignore_errors: true
  tags:
    - skhd

- name: Bootstrap skhd launchd service
  shell: launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/com.koekeishiya.skhd.plist
  ignore_errors: true
  tags:
    - skhd

- name: Enable skhd service to start at login
  shell: launchctl enable gui/$(id -u)/com.koekeishiya.skhd
  ignore_errors: true
  tags:
    - skhd
