# - name: Slack - install
#   become: true
#   mac_pkg:
#     pkg_type: app
#     url: https://downloads.slack-edge.com/releases/macos/4.33.90/prod/arm64/Slack-4.33.90-macOS.dmg
#     archive_type: dmg
#     archive_path: "Slack.app"
#   tags:
#     - slack
#     - install
#     - macos
