- name: Superpower exists
  shell: mkdir -p {{ work }}
  tags:
    - work-project

- name: Superpower
  ansible.builtin.git:
    repo: 'git@github.com:superpowerdotcome/superpower.git'
    dest: "{{ work }}/superpower"
  tags:
    - work-project
